### ISSUE TITLE
Installation instructions are wrong, environment.yml has some issues.

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_sim#108]
The reference a non-existent conda yaml file: `conda env create -f travis-environment.yml`. Note that this same mistake is made in the contributing guidelines.

I presume you mean to refer to the file `environment.yml`, which seems to have some packages that you don't need (nose, future -- you only seem to support python 3) and it's missing `astropy`, which is required by pyuvdata, but since you're installing that via pip you may end up with a pip installation of astropy rather than a conda installation, which is definitely not optimal (an aside: yhy are you installing pyuvdata via pip rather than conda?). Also, the `environment.yml` file lists `healpy` and `astropy-healpix`, but only the latter appears in `setup.py` -- is `healpy` actually required? Same question for `numba` and `basemap`.

**Comment by bhazelton** [comment]
Ok, I am wrong about nose and future, they appear to be required (tests fail without them), but I don't understand why since you use pytest and appear to only support python 3.

**Comment by r-pascua** [comment]
I think in the past, `nose` was used for testing, but there was a gradual shift toward `pytest` without updating all of the tests to stop using `nose`. We'll make the shift to drop `nose` entirely by the version 1 release. We also haven't completely dropped python 2 support; I believe most of the `VisibilitySimulator` stuff needs to be updated to python 3. I believe we also have a version 1 milestone to drop python 2 support.

**Comment by bhazelton** [comment]
Ok, then why are you only testing against python 3?

**Comment by r-pascua** [comment]
Good question. My understanding is that at some point we had stopped developing in python 2 and testing against it since most of the features had been ported over to python 3, but I think the more accurate visibility simulator was developed in python 2 and we didn't have the people available to port it to python 3 before merging. Either way, I understand that it's sloppy and should be fixed.

@steven-murray can you comment?

**Comment by aelanman** [comment]
For what it's worth, healvis has been python-3 only since last December. Which simulator hasn't been ported?

**Comment by r-pascua** [comment]
I think the stuff in `vis_cpu` was initially written for python 2, though I'm not sure of its current status. I've been out of the loop on developments on that end, so I'm not sure if healvis was the blocking point on porting to python 3, or if there were some code in `hera_sim` that was actually written for python 2.

**Comment by steven-murray** [comment]
I *think* everything works for python 3, and python 2 is not supported, but yeah, we're kinda lumping everything into the v1 release, which should happen soon. Documentation is from a while ago, and the installation instructions should definitely be updated for the new release. Thanks for making the issue!
