### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_sim#109]
There's no license on this repo.

Note that we usually use a permissive open source license for HERA repos (e.g. BSD or MIT). But that may not be allowed if you are actually using healpy (which has a copy-left license).

**Comment by r-pascua** [comment]
Looks like there are quite a few places in the `visibilities` module where we use `healpy`. If we switch to `astropy-healpix`, then would we be okay for an open source license?

**Comment by bhazelton** [comment]
Yes. I should clarify, both astropy-healpix and healpy use open source licenses. The difference is whether they are permissive or copy-left licenses.

**Comment by aelanman** [comment]
@r-pascua It won't be possible unless healvis switches to astropy-healpix, which will be difficult. `healvis` uses the spherical harmonic transforms/interpolation methods in healpy, which are not yet available in astropy-healpix. I may be able to make it an optional dependency for those features and switch to using astropy-healpix for the core functionality?

(Technically, healvis violates the GPL, because it uses healpy but is BSD. Nobody's arrested me yet, but I would like to make sure everything's proper.)

**Comment by r-pascua** [comment]
Gotcha, thanks for the clarifications @bhazelton and @aelanman. So the takeaway I'm getting from this is that currently, we're not able to have a permissive license, though we can have a copy-left license? (I don't understand the difference, but I'll ask google for help on that.)

@steven-murray thoughts on what to do?

**Comment by steven-murray** [comment]
I actually thought I made a PR that added an MIT license not so long ago... I probably merged it into the v1.0.0 branch. I think, on @bhazelton's advice, we want to stick away from GPL, but we do need healpy (or at least, `astropy-healpix`), and we do wrap `healvis` and essentially use all of its functionality.

@bhazelton can you clarify if the GPL license specifies that a code wrapper also requires having GPL? Like, if we're not copying any code explicitly, or even really using the functionality other than by injection, does it still mean we need GPL?

**Comment by bhazelton** [comment]
I guess for this repo I'd suggest removing the healpy import if possible so that you're not calling it directly -- then when healvis updates this one will get it for free and you can let healvis worry about the non-compliance with the license.

**Comment by bhazelton** [comment]
My understanding is that if you import it you have to have GPL.

**Comment by steven-murray** [comment]
OK. I'll make a PR to either change to GPL or remove healpy. I think I'll have it pull into v1.0.0 -- will that be fine, or should I get it straight into master?

**Comment by bhazelton** [comment]
I think that's fine. But we need to have a hard think before going to GPL. That would require that any repos that import hera_sim would also need to be GPL.
