### ISSUE TITLE
Do fringe-rate/delay filtering with uvtools?

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#124]
Just putting feelers out there for the possibility of updating `utils.rough_fringe_filter` and `utils.rough_delay_filter` to optionally use `uvtools.dspec.fourier_filter`. This wouldn't make it depend entirely on `uvtools`, but rather give the user the option to use `uvtools` for filtering. I suspect that the caching used in `uvtools.dspec.fourier_filter` could potentially speed up simulations managed by the `Simulator` class, though I do need to test this hypothesis. Any thoughts on this, @steven-murray or @nkern?

**Comment by steven-murray** [comment]
I would *prefer* not to rely on `uvtools` if we can get away with it. If the performance of that function is significantly better though...

**Comment by r-pascua** [comment]
I understand not wanting to rely on `uvtools`. This was more of a "what if" thing that came to mind as I was rewriting the tests for the fringe/delay filters. At the very least, I think it's possible to get a speedup for `Simulator` managed simulations by refactoring the code in `utils` a bit and adding delay/fringe filters to the `Simulator` class as cached properties (the only downside here is the `Simulator` object would use a bit more memory). So maybe I could add that as a todo for a future release?

**Comment by steven-murray** [comment]
that sounds reasonable to me!
