### ISSUE TITLE
Refactor `utils`, add filter cached property to `Simulator`

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#125]
Refactor the `utils.rough_<delay/fringe>_filter` functions so that a pre-computed filter may be used (rather than having a new filter be calculated each time) and update the `Simulator` class to keep a cache of delay/fringe filters relevant for the given setup. It may be best to leave this as an optional functionality, in case the simulation is running up against memory limits without a cache of filters (for example, in a HERA-350-like simulation). Backwards compatibility should be maintained when refactoring the filter functions.

**Comment by steven-murray** [comment]
This functionality was added to utils in #132, but adding the cache to the simulator looks too tricky with the current setup of the simulator. I propose leaving that to the future. Will keep this open as a reminder.
