### ISSUE TITLE
Add docstrings for class attributes

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#134]
It would be useful to have the values of some class attributes be visible in the `class` table on the API reference (e.g. the `is_multiplicative` attribute of classes like `Bandpass` or `NoiselikeEoR`, or the `diffuse_ability` attribute of the `VisibilitySimulator` class). We should be able to achieve this by adding docstrings to these class attributes, with the docstrings only containing the value of the attribute. If possible, it would be nice to figure out how to make this work with as little dev overhead as possible.

**Comment by steven-murray** [comment]
I think this is done in v1. @r-pascua ?

**Comment by r-pascua** [comment]
Sort of, but not in the way I would have liked. I'm not so sure that what I wanted (the ability to determine the value of these at a glance) is really possible. I'm going to close this issue though, since I don't think trying to implement exactly what I'm imagining is worth the effort.
