### ISSUE TITLE
Modify how defaults are handled

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#135]
The defaults handling should have the following features:

- Not too many layers of abstraction; easy for developers & users to understand
- Not require unique parameter names for each function  **implement this before v1 release**
- No unintended consequences (e.g. forgetting parameter names already exist when writing new function)
- Minimal entries in configuration; no need for duplication
- Allow for switching between sets of defaults with a single command
- Clear documentation; minimal manual documentation of parameter defaults

Potential ideas for implementing modifications:

- Limit scope to something like the  `Simulator` class
  - Pros: limits scope of failure/unexpected behavior
  - Cons: doesn't necessarily solve the issues with current implementation; loses support for using defaults without using `Simulator` class
- Have a `Config` class/module that can read defaults and get parameters to explicitly access that config for setting defaults, using our own singleton `None`-like object as the hard-coded default
  - Pros: less abstraction; defaults are set where they are used; don't require unique parameter names; avoids duplication
  - Cons: requires a little more work on developer side; parameter defaults need to be explicitly written in docstring; slightly less obviously-pythonic code
- Figure out how to slightly modify the `Defaults` class to meet the desired features
  - Pros: most of the scaffolding is already in place; requires least effort on part of developer; no change to user; every default is fair-game
  - Cons: not clear which default is being used on inspecting function signature; not clear if there is an obvious way to meet every desired feature

Potential source of inspiration: matplotlib's `rcParams` and `use_style`

**Comment by steven-murray** [comment]
@r-pascua have we decided on this? I mean, we've merged v1, and it works well. Perhaps we can close this?

**Comment by r-pascua** [comment]
Hmm. I'm hesitant to want to attempt to implement this, because honestly getting the whole defaults-switching business correct is very difficult. I think it's important to keep the stuff posted here in mind, but I really don't mind if we close this for now. So I won't complain if we close this issue.

**Comment by steven-murray** [comment]
Yeah I think it's something we can circle back to if necessary.
