### ISSUE TITLE
Choosing antenna beams is kinda buggy

### ISSUE THREAD

**Issue by steven-murray** [HERA-Team/hera_sim#137]
beam handling is slightly buggy; it's possible to input `beams=None` and `beam_ids=[0, 1, 2]`, which will cause an error later on. May not be checked fully.

**Comment by steven-murray** [comment]
@hughbg will check if this is still an issue after recent updates.

**Comment by hughbg** [comment]
There is a line in hera_sim simulators.py that will create uniform beams for the antennas if beams=None. https://github.com/HERA-Team/hera_sim/blob/a59095859f0fc51cc2b0d833ab80ebe29ab79b77/hera_sim/visibilities/simulators.py#L170 Below that is also a line that creates beam_ids if beam_ids=None. 

Then there are checks in vis_cpu.py to make sure the lists match up: https://github.com/HERA-Team/hera_sim/blob/a59095859f0fc51cc2b0d833ab80ebe29ab79b77/hera_sim/visibilities/vis_cpu.py#L98

Here are some tests where beams, beam_ids are set to different things: None, single objects, lists of the wrong length:
<table>
<tr><td>   Test condition </td><td>   Result </td></tr>
<tr><td> beams=None,       <br>             beam_ids=None         </td><td>                Ok, everything created </td></tr>
<tr><td> beams=[valid],   <br>    beam_ids=None          </td><td>                  "        "   </td></tr>
<tr><td> beams=None,    <br>   beam_ids=[valid]                 </td><td>                  "        "  </td></tr>
<tr><td> beams=None ,   <br>   beam_ids=[one integer, not list] </td><td>    Not checked for in code.<br><br>File "/users/hgarsden/anaconda3_herasim/lib/python3.7/site-packages/hera_sim/visibilities/vis_cpu.py", line 100, in __init__
    if len(self.beams) != len(self.beam_ids):
TypeError: object of type 'int' has no len()
</td></tr>
<tr><td> beams=[one beam object, not list],   <br>    beam_ids=[valid] </td><td>  Not checked for in code.<br><br>  File "/users/hgarsden/anaconda3_herasim/lib/python3.7/site-packages/hera_sim/visibilities/vis_cpu.py", line 100, in __init__
    if len(self.beams) != len(self.beam_ids):
TypeError: object of type 'PerturbedPolyBeam' has no len()
</td></tr>
<tr><td> beams=[valid],    <br>      beam_ids=[list, wrong length]  </td><td> Checked for in code.<br><br>
   File "/users/hgarsden/anaconda3_herasim/lib/python3.7/site-packages/hera_sim/visibilities/vis_cpu.py", line 106, in __init__
    % (len(self.beams), len(self.beam_ids))
ValueError: Specified 10 beams for 2 antennas
</td></tr>
<tr><td> beams=[list, wrong length],   <br>       beam_ids=[valid] </td><td> Checked for in code.<br><br>
    File "/users/hgarsden/anaconda3_herasim/lib/python3.7/site-packages/hera_sim/visibilities/vis_cpu.py", line 106, in __init__
    % (len(self.beams), len(self.beam_ids))
ValueError: Specified 2 beams for 10 antennas
</td></tr>
</table>
