### ISSUE TITLE
HealVis wrapper off by a factor of 2 wrt pyuvsim and vis_cpu

### ISSUE THREAD

**Issue by steven-murray** [HERA-Team/hera_sim#151]
Noticed by @philbull -- when dealing with polarization, it's better to deal individually with linear pols, rather than stokes I. I think HealVis deals with stokes I, and is therefore off by a factor of 2 from the other simulators. We need it to be consistent in the wrapper, so I'd say the best course of action is just to fix the amplitude in the wrapper. 

@aelanman can you confirm this?

**Comment by aelanman** [comment]
Yes, `healvis` computes pseudostokes I visibilities.

**Comment by steven-murray** [comment]
Done in #174
