### ISSUE TITLE
rfi stations appear to be off by a bin?

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_sim#16]
For example, if I look at the HERA_RFI_STATION at 183.1 MHz, it looks like this in the data:
![image](https://user-images.githubusercontent.com/4752917/50314545-6f316d00-046c-11e9-86c5-173007104ada.png)

But simulating it with HERA sim, it shows up here:
![image](https://user-images.githubusercontent.com/4752917/50314557-7ce6f280-046c-11e9-92ae-d3effd9336ac.png)

It looks to me like the station is off by a bin - maybe an indexing issue, maybe it's just at the wrong frequency.

**Comment by steven-murray** [comment]
Hi Adam, can you post the code you used to make the plot? Is the frequency binning the same in both data and sim?

**Comment by adampbeardsley** [comment]
Hm, trying to recreate this, I'm coming to realize it's likely just an overly simple RFI model. I don't recall what file I was looking at previously, so I just grabbed another (random) one. Here's the code I used:
```
uv = UVData()
# use whatever file you have...
uv.read('/Users/abeardsley/code/hera/hera_sim/zen.2458098.66239.yy.HH.uv/')
rfi_narrow = rfi.rfi_stations(uv.freq_array[0, :]*1e-9, np.unique(uv.time_array))

plt.figure()
extent = [uv.freq_array.min()*1e-6, uv.freq_array.max()*1e-6, 0, 1]
ax1 = plt.subplot(211)
plt.imshow(np.abs(uv.get_data([1, 2, 'yy'])), aspect='auto', extent=extent)
plt.clim([0, 1])
ax2 = plt.subplot(212, sharex=ax1, sharey=ax1)
plt.imshow(np.abs(rfi_narrow), aspect='auto', extent=extent)
```
With this file, the RFI looks a bit different (data on top, sim on bottom):
![image](https://user-images.githubusercontent.com/4752917/51064314-478d7a80-15bc-11e9-85a9-637ae3cc4238.png)

So I think in the example I had before, the lower part of this relatively wide signal was quieter. But in reality we need a more dynamic model to accurately capture the data.

I'll close this for now, but I am still working on a better model as I mock up a benchmark set for xrfi.
