### ISSUE TITLE
Fix `VisibilitySimulator` Tutorial

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#166]
This hasn't been updated in a while and it seems like there are some issues. I'll do my best to document my findings thoroughly.

First, I am setting up my environment as follows:
* Navigate to top-level directory of `hera_sim`
* Do `conda env create -f ci/tests.yaml -n vis_testing` and activate the environment.
* Then install `hera_sim` via: `pip install .`
* Install `jupyter` so I can run the tutorial notebooks: `conda install jupyter`
* Update packages for good measure: `conda update -n vis_testing --all`

Here are the relevant details of the environment:
```
# Name                    Version                   Build  Channel
hera-sim                  1.0.3.dev12+gced8329.d20210719          pypi_0    pypi
healvis                   2.0.1.dev58+g9c17ef4          pypi_0    pypi
pyradiosky                0.1.2                    pypi_0    pypi
pyuvdata                  2.1.5            py39he80948d_0    conda-forge
pyuvsim                   1.2.1.dev117+g630cb43.main          pypi_0    pypi
vis-cpu                   0.2.1                    pypi_0    pypi
```

Now onto the tutorial. I'll start with a high-level summary of the issues that need to be fixed, then go into detail on each of them.

1. The various calls to `io.empty_uvdata` need to be updated. The two places this function is explicitly called are in the `myuvdata` function, and in the cell initializing the `UVData` object for use in the HERA-37 simulation.
2. The tutorial still uses `healpy` rather than `astropy_healpix`. This conversion is not exactly trivial, but shouldn't be *too* difficult.
3. The plotting section for the HERA-37 simulation is broken, since the call to recover the blt indices doesn't set `ordered=False`.
4. Following up on the above, the way plotting is handled is not robust. blt indices are retrieved typically by using the `antpair2ind` method, with the setting `ordered=False`. While this is inconsequential if we're only considering the amplitude of the visibilities, this will get the phases wrong in cases where the conjugate to the requested baseline has data.
5. The outputs of the `vis_cpu` simulations no longer agree with those of the `healvis` simulations in any of the provided examples. The currently-rendered version of the notebook has agreement to within about 1%, but re-running the notebook (after fixing basic errors due to e.g. API changes) results in errors as large as ~100%. I do not currently have enough familiarity with either package to figure out why these errors exist.
6. The example using a simulation built from a `pyuvsim`-style configuration file is fubared. I think fixing this shouldn't be too much trouble, but I don't know how to fix it off the top of my head (I'd have to go and reference the `pyuvsim` docs).

Now, here are the issues in a bit more detail.

1. The outdated call to `io.empty_uvdata`. Below I provide an example of minimal changes to the `myuvdata` function that fixes this. The broken call to `io.empty_uvdata` in the HERA-37 simulation section can be fixed in a similar manner.
```
def myuvdata(ntimes=48, nants=2, start_freq=140e6, channel_width=100e5, **kwargs):
    
    # Choosing antenna postions in a deterministic way
    ants = {}
    for i in range(nants):
        ants.update([(i, (-(i % 3), i, i % 4))])
      
    return io.empty_uvdata(
        Nfreqs=5,
        start_freq=start_freq,
        channel_width=channel_width,
        integration_time=sday.to('s')/ntimes,
        Ntimes=ntimes,
        array_layout=ants,
        **kwargs
    )
```

2. We should be able to get around most issues regarding `healpy` by just doing `from astropy_healpix import healpy`, though there are some things that will need to change in a non-trivial way. In particular, the call to `healpy.query_disc` in the `half_uniform_sky` function will need to be updated, as will the call to `healpy.get_nside` in the `align_src_to_healpix` function. I think the best practice, though, is to use the methods provided by the `VisibilitySimulator` (I assume this notebook was written before those features were added).

3. A simple fix is to set `ordered=False`, but I do not recommend doing that. I think the better way to fix this is to just use the `UVData.get_data` method for retrieving the desired visibilities.

4. Basically the same note as above. The `VisibilitySimulator.simulate` method adds the simulated data to the underlying `UVData` object's `data_array`, so there's no reason to fuss with figuring out how to slice through the array.

5. Below I've provided a screenshot showing the disagreement (top). I've also provided a screenshot of the current rendering of the notebook for reference (bottom). Below both of those images, I provide a suggested new plotting function to make visual inspection of the non-differenced plots easier. This updated plotting function was used to make the top figure. I suppose it is worth providing some of my commentary, so here it goes:
* Before getting into the details, here's my conclusion: the sorting on the data used by `healvis` does not match the sorting of the `data_array` referenced by the `VisibilitySimulator`. I'm not sure how to fix this, but I'm certain that this is one of the issues. The other issue is a factor of two error, likely in the definition of the beam (since there's a silent alteration of the beam used by `healvis` relative to the one defined when a `VisibilitySimulator` instance is created).
* Point 1: mismatch in the sorting of the two different data arrays. This is inferred by inspecting the top two plots in the top figure. Note that the line for `ant_1, HealVis` in the top plot has roughly the same shape as the line for `bl(0,2), VisCPU` in the middle plot. This suggests that the ordering imposed by `healvis`, which is found on line 399 in `healvis/observatory.py` to be: `np.lexsort((baseline_inds, time_inds))`, does not match the default ordering used when making a `UVData` object with `io.empty_uvdata`.
* Point 2: factor of two error in the visibilities. This can be seen by again inspecting the top and middle plots in the top figure. Both the auto-correlations and the cross-correlations that come out of `healvis` look to be a factor of 2 greater than those coming from `vis_cpu`. Just compare the lines that have roughly the same shape.

![vis_cpu_vs_healvis_multiple_src](https://user-images.githubusercontent.com/29933285/126268139-aa8c1915-5298-4093-85ed-0fa30d1232b3.png)

![vis_cpu_vs_healvis_old](https://user-images.githubusercontent.com/29933285/126268158-b592f3bb-9236-498b-b55e-a301420d2e89.png)

```
def compare_blts(simulator1, simulator2):
    colors = plt.cm.tab10.colors
    fig, ax = plt.subplots(
        nrows=3,
        ncols=1,
        sharex=True,
        subplot_kw={"ylabel":"|Visibility| [Jy]"},
        figsize=(16, 12)
    ) 
    name1 = type(simulator1).__name__
    name2 = type(simulator2).__name__
    fig.suptitle(f"{name1} vs {name2}", fontweight='bold')
    
    lsts = np.unique(simulator1.uvdata.lst_array)
    
    for i in simulator1.uvdata.antenna_numbers:
        auto1 = np.real(simulator1.uvdata.get_data(i,i,'xx')[:,0])
        auto2 = np.real(simulator2.uvdata.get_data(i,i,'xx')[:,0])               
        ax[0].plot(lsts, auto1, label=f"ant_{i}, {name1}", color=colors[::-1][i], alpha=0.6)
        ax[0].plot(lsts, auto2, ls="--", label=f"ant_{i}, {name2}", color=colors[::-1][i], alpha=0.6)
        
        for j in simulator1.uvdata.antenna_numbers[(i+1):]:
            k = i * len(simulator1.uvdata.antenna_numbers[1:]) + j
            bl = (i,j)
            cross1 = np.real(simulator1.uvdata.get_data(i,j,'xx')[:,0])
            cross2 = np.real(simulator2.uvdata.get_data(i,j,'xx')[:,0])       
            ax[1].plot(lsts, cross1, label=f"bl{bl}, {name1}", color=colors[k], alpha=0.6)
            ax[1].plot(lsts, cross2, linestyle="--", label=f"bl{bl}, {name2}", color=colors[k], alpha=0.6)
            ax[2].plot(lsts, cross2 - cross1, label=f"bl{bl}, Difference", color=str(k/(k+1)))
        
    [a.legend() for a in ax]
    ax[0].set_title("Autocorrelations")
    ax[1].set_title("Cross-Correlations")
    ax[2].set_title(name2 + " Cross-Correlation minus " + name1 + " Cross-Correlation")
    ax[-1].set_xlabel("LST [rad]")
```

6. The `data/obsparam_example.yml` file no longer exists: the extension has been changed from `yml` to `yaml`. This change is not enough to solve the problem, though. The tutorial currently tries to specify source positions and fluxes in addition to the obsparam file, which causes the `VisibilitySimulator` to raise an issue. Simply leaving these parameters out does not fix the issue either, but rather causes `pyuvsim` to complain that either a Julian Date needs to be specified for the mock catalog, or that an input `UVData` object must be provided (which I *think* means a path to a file that can be loaded into a `UVData` object).

**Comment by steven-murray** [comment]
Thanks @r-pascua, this is extremely comprehensive. I think the best course of action will be to update the tutorial as part of the `visibility-simulator-overhaul` branch, since that involves several API changes as well. 

Do you need anything short-term?
