### ISSUE TITLE
Update Tutorial Notebooks

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#180]
Many of the tutorial notebooks are outdated, and some could also be updated to be clearer in how they present material. When addressing this issue, or shortly thereafter, #84 should be addressed so that we know when an update breaks a notebook.

**Comment by steven-murray** [comment]
@r-pascua is this closed now?

**Comment by r-pascua** [comment]
For the most part, yeah. I think we could do with updating the `hera_sim_tour` notebook, but I suppose it's not a huge priority. I could also stand to update the defaults and CLI tutorials, but I think that's very low priority. I *think* we can close this, but I want to push for #84 getting addressed somewhat soon so we automatically know when a notebook is out-of-date.

**Comment by steven-murray** [comment]
I agree. I'll make sure the priority of that one is bumped up, and close this. I think issues without other outdated docs will be discovered in fixing #84.
