### ISSUE TITLE
Update sim_red_data to use pyuvdata standard antenna polarization strings

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_sim#19]
https://github.com/HERA-Team/hera_sim/blob/87abb985f5092cac32615d022b8be84c071b0596/hera_sim/vis.py#L166

The version in hera_cal (and yes, we should eventually merge these!) does this: https://github.com/HERA-Team/hera_cal/blob/86907a511dfa2d9499ed36e83e7ebcd56643d33f/hera_cal/redcal.py#L50

**Comment by steven-murray** [comment]
@jsdillon this has been done, right?

**Comment by jsdillon** [comment]
Uh, probably. There's no version in hera_cal anymore.

**Comment by steven-murray** [comment]
Good enough for me. Reopen if necessary.
