### ISSUE TITLE
Bug in UVSim beam_dict parsing

### ISSUE THREAD

**Issue by piyanatk** [HERA-Team/hera_sim#191]
`ModelData._process_beam_ids` returns a dictionary, not an array of integer as indicated in the typing.

https://github.com/HERA-Team/hera_sim/blob/153eef4cb1d0b38666791a116187f106ab115fb2/hera_sim/visibilities/simulators.py#L116-L143

This causes an error in `UVSim.simulate`, which expects an integer array of beam_ids.
https://github.com/HERA-Team/hera_sim/blob/153eef4cb1d0b38666791a116187f106ab115fb2/hera_sim/visibilities/pyuvsim_wrapper.py#L20-L25

`VisCPU` is currently working okay (with the dictionary `beam_ids` passed from `ModeData`).

**Comment by piyanatk** [comment]
Thanks for for the commit @steven-murray. Unfortunately, it did not fix the issue with `UVSim`, which I should have been more clear. 

The problem is that, if you have a pyuvsim config file these in the array layout config,
```
Name	Number	BeamID	E	N	U
ANT0	0	0.0	-105.0353015473961	-110.7220528607248	0.9381711974937303
ANT1	1	0.0	-90.42745888420856	-110.6662643333309	0.9283957723292957
ANT2	2	0.0	-75.81961648211627	-110.61047580628116	0.9185869222903591
ANT11	11	0.0	-112.38751908856237	-98.10314445832503	0.7882534026380057
ANT12	12	0.0	-97.77967572985466	-98.04735521461419	0.7184946875553564
ANT13	13	0.0	-83.17183303826486	-97.9915661250264	0.6587025492404806
ANT14	14	0.0	-68.5639929817703	-97.935780119385	0.7988769889873808
```

and then initialize a ModelData instance with the config file,
```python
data_model = ModelData.from_config(config_file)

```
you will get this as the `beam_ids`.
```python
print(data_model.beams_ids)
# -> {'ANT0': 0, 'ANT1': 0, 'ANT2': 0, 'ANT11': 0, 'ANT12': 0, 'ANT13': 0, 'ANT14': 0}
```
It is already in an expected dictionary format - the keys are antenna names, and the values are BeamIDs. These keys _cannot_ be mapped to integer values. 

So the these lines will give `KeyError` because `idx is just integer, and they are actually not needed.
https://github.com/HERA-Team/hera_sim/blob/153eef4cb1d0b38666791a116187f106ab115fb2/hera_sim/visibilities/pyuvsim_wrapper.py#L22-L25

**Comment by steven-murray** [comment]
@hughbg if you have a fix, that'd be great!

**Comment by piyanatk** [comment]
@steven-murray Can you fix this in #237? I have updated my comment above to make the issue more clear. It is such a small fix that I don't want to open a new PR for it unless you think that is a bad idea.

**Comment by steven-murray** [comment]
@piyanatk is the fix just to replace `str(idx)` with `ant` in `data_model.beam_ids[str(idx)] ` ?

**Comment by piyanatk** [comment]
Yep!

**Comment by steven-murray** [comment]
Done.
