### ISSUE TITLE
First-Order Array Element Coupling (Mutual Coupling) Algorithm

### ISSUE THREAD

**Issue by alphatangojuliett** [HERA-Team/hera_sim#196]
After some discussion, Steven and I feel that the first-order coupling algorithm presented in [2110.10879](https://arxiv.org/abs/2110.10879) can be incorporated into hera_sim. 

Basic structure: input into the algorithm non-coupled, simulated visibilities in  .uvh5 file format. Output the same visibilities, but with coupling according the the first-order algorithm. 

Here you can find the [functions](https://github.com/alphatangojuliett/CoupledRadioInterferometer/blob/master/CoupledRadioInterferometer/Functions/first_order_coupling_functions.py) associated with the first-order semi-analytic mutual coupling code, which were discussed in the datacon on October 29th 2021. These are the functions I would intend to incorporate into hera_sim.

A [demo](https://github.com/alphatangojuliett/CoupledRadioInterferometer/blob/master/tutorials/first_order_coupling_demo.ipynb) of how to use that code is in the tutorials section of the repository. The repo also has a link to the semi-analytic coupling paper, which has been submitted to MNRAS. The '[FOC_plotting_funcs](https://github.com/alphatangojuliett/CoupledRadioInterferometer/blob/master/CoupledRadioInterferometer/Functions/FOC_plotting_funcs.py)' script may be useful for handling data and making plots, but has hera_pspec as a dependency, and so probably doesn't want to live in hera_sim.

The functions script contains both a multi-thread-capable version of the coupling algorithm as well as a non-multi-threaded version. The demo hyperlinked above uses the multi-threaded version of the code; implemented via concurrent.futures

**Comment by piyanatk** [comment]
Awesome @alphatangojuliett. I am interested to help getting this implemented. I think it might be nice if you can schedule a zoom call with some of us and walk us through the codes. Then, we can brainstorm how to implement it (if @steven-murray  haven't thought about it already :)). I will try to look through the codes over the next few week or so too.

@steven-murray , I made a new H4C milestone for this and add several tags. Please feel free to change if they aren't right.

**Comment by r-pascua** [comment]
Closing this, as it was implemented in version 3.1.0.
