### ISSUE TITLE
URLs starting with "git://" in setup.cfg need to be changed to "https://"

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_sim#219]
Github no longer supports these urls so pip fails trying to install hera_sim.

See https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by bhazelton** [comment]
I made this because I'm seeing an error in pyuvsim testing, but I just realized that testing is actually not breaking because of this (although this is still an issue) because we use the `--no-deps` flag when we pip install hera_sim. The problem is actually lower down in the HERA stack, in uvtools and probably other places.

**Comment by bhazelton** [comment]
Update: the hera_cal issue has now been fixed, so our test on pyuvsim works. But I think these URLs should be changed.

**Comment by philbull** [comment]
Fixed in #220
