### ISSUE TITLE
Pin `puuvdata>=2.4.0`

### ISSUE THREAD

**Issue by piyanatk** [HERA-Team/hera_sim#271]
Is there anything else that prevent us to pin `pyuvdata>=2.4.0`. This version fixed [the discontinuity bug in the LST uvdata calculation](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/pull/1314), which significantly affect the visibility simulation via `vis_cpu`.

**Comment by steven-murray** [comment]
I think this is fine. I'll do that and make a new release as requested in #270
