### ISSUE TITLE
Issue with rfi_scatter implementation and docstring.

### ISSUE THREAD

**Issue by chrisfinlay** [HERA-Team/hera_sim#32]
Phase for scattered RFI only drawn from u[0,1] not u[0,2*pi]. 
Docstring description seems to be wrong too.

**Comment by steven-murray** [comment]
Thanks for pointing it out. Does 0bec71d822e7bd690b84ed8f1d4e5745739443eb fix the problem?

What about the docstring seems wrong?

**Comment by steven-murray** [comment]
Closing due to no reply. Open again, if it is an issue.
