### ISSUE TITLE
HA compute in point source modeler looks suspicious

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_sim#35]
https://github.com/HERA-Team/hera_sim/blob/81603f966150b6d49f03eaf9aa69a125d8a263d7/hera_sim/foregrounds.py#L120

We're seeing `foregrounds.pntsrc_foreground` produce zeros, including in the example notebook (where before/after adding point sources looks identical). My suspicion is the line above isn't right, and should be using the RAs of the sources, not 0.

**Comment by steven-murray** [comment]
I feel like @nkern will know...

**Comment by steven-murray** [comment]
This is a bit mysterious. We're going to try to solve it for sure in the context of #85.
