### ISSUE TITLE
Simulator.add_foregrounds Polarization Issue

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#55]
The `Simulator.add_foregrounds` method will not work correctly when trying to simulate diffuse foregrounds for two different polarizations. The current implementation will calculate diffuse foregrounds appropriate for a single polarization and apply the result to all polarizations. For example, if we instantiated a `Simulator` object with `polarization_array=['xx','yy']`, then ran `add_foregrounds('diffuse_foregrounds', Tsky_mdl=hera_sim.noise.HERA_Tsky_mdl['xx'])`, then both the xx- and yy-polarizations would have foregrounds calculated for the xx-polarization.

I can implement a quick-fix for this if we expect this to be the only place we'll add in polarized simulation components; otherwise, we should determine a more general approach to correctly handling multiple polarizations.

**Comment by steven-murray** [comment]
Let's think about a more general approach. I'll add this to my to-do list.

If the `diffuse_foregrounds` function just accepted a polarization string, that would be enough, right?

**Comment by r-pascua** [comment]
Not quite; I think it would be better to have the various `add_` methods take a polarization string.

Modifying `diffuse_foreground` in the way you suggest wouldn't quite work, unless it was modified so that the `Tsky_mdl` kwarg was passed as a dictionary, but that would break the current API.

**Comment by steven-murray** [comment]
But if the `Tsky_mdl` is just taking a `Tsky` object, couldn't we then internally pass the polarization to that object?

**Comment by r-pascua** [comment]
If we updated models which have a `Tsky_mdl` argument to only use `Tsky` objects, then yes, we could do that; however, I've been working on the assumption that `Tsky_mdl` will be passed as a `scipy.interpolate.RectBivariateSpline` object in order to not break backwards compatibility.

I can probably figure out a way to work with either case so that we don't break the API. If you think this is a worthwhile thing to do, then I'll start working on it.

**Comment by steven-murray** [comment]
I think that if this is implemented in the context of #54 , we can allow this breaking of the API. I don't think there are a large number of people who are using this at the moment, so it will be only a little effort on their part to fix their code. 

We should make sure that the update with that PR is very well documented though (as in, in a changelog).
