### ISSUE TITLE
take into account baseline orientation for diffuse and pt source modeling

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_sim#8]

**Comment by steven-murray** [comment]
I've partially addressed this in 4fa653aafac716284b19c5ee896d306b40bf3448 and aac56b6772e7b0550da4dc88dbbbd62025265717. I've changed the utility functions to optionally accept a *vector* of baseline lengths, and act accordingly.

I have not yet addressed this in the context of the ``pntsrc_foreground`` function, which I cannot for the life of me understand the workings of. Will submit a PR for the better-foregrounds branch when I have also fixed this function.

**Comment by steven-murray** [comment]
The PR for better-foregrounds has now been merged, but this has *not* been fixed for the ``pntsrc_foreground`` function. Will comment back when this fix is in place.

**Comment by steven-murray** [comment]
This was fixed by #30 which is now merged.
