### ISSUE TITLE
TypeError: 'float' object is not callable in Diffuse Foregrounds in tutorial file

### ISSUE THREAD

**Issue by musicbyjing** [HERA-Team/hera_sim#80]
Hello there,

In the file `hera_sim/docs/tutorials/hera_sim_tour.ipynb`, there's an issue when I try to run the cell immediately below "Foregrounds / Diffuse Foregrounds". The error is attached, but it appears to be an issue with one of the functions in the hera_sim code. I have not changed anything in the file, and all code before this line works fine.

![image](https://user-images.githubusercontent.com/39681037/74197085-b197a980-4c2c-11ea-9ab9-5a9e8b322583.png) 

Thanks in advance!

**Comment by r-pascua** [comment]
Ah, looks like the notebook is out of date--sorry about that. For now, please just reorder the parameters in the call to the function as `diffuse_foreground(lsts, fqs, bl_len_ns, Tsky_mdl)`. I will make a separate issue for updating the tutorial notebook.

**Comment by musicbyjing** [comment]
Sorry, but that just brings up a new issue:

![image](https://user-images.githubusercontent.com/39681037/74203903-2a076600-4c3f-11ea-984f-2fdb85930a03.png)

**Comment by r-pascua** [comment]
Make `bl_len_ns` an array-like object (simplest thing to do is make it a list). Sorry for the problems, but these will be fixed when #81 is addressed.

**Comment by musicbyjing** [comment]
I see, that's very helpful. Thank you!

**Comment by r-pascua** [comment]
Yep! Sorry for the troubles&mdash;we should have been on top of this!
