### ISSUE TITLE
Update Tutorial Notebooks

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#81]
Some of the tutorial notebooks may have bad function calls after some of the new changes had been implemented. In particular, the `hera_sim_tour` notebook has an incorrect call to `diffuse_foreground`. This should be fixed.

**Comment by steven-murray** [comment]
I think this brings up a wider concern: we want our notebooks to be up-to-date for any commit. I wonder if there's some way we can put them through CI?

**Comment by r-pascua** [comment]
If there's a way to run an entire notebook from the command line, then we should be able to put them through CI. In case we can't, then I think the best practice would be to make sure to run each of the tutorial notebooks and fix any bugs before finalizing any PRs.

**Comment by r-pascua** [comment]
After a quick search, I found that the following command can execute a notebook from the command line:
`jupyter nbconvert --execute <notebook>`

So we can include a routine in CI that executes this command for each of the tutorial notebooks; however, there are a few things we'll need to consider. First, this adds both `jupyter` and `nbconvert` as dependencies&mdash;I don't see this as much of a problem, but it's worth noting. Second, if the notebook was last opened using Py2 and the command is run in a Py3 environment, then it will immediately error out.

As an alternative, we can make a test script for this that gets run with the rest of the tests. Here's a quick outline of how we can do that:
```
import os
import hera_sim

def test_tutorial_notebooks():
    base_path = os.path.split(hera_sim.__path__[0])[0]
    nb_path = os.path.join(base_path, "docs/tutorials")
    nb_names = [nb for nb in os.listdir(nb_path) if nb.endswith(".ipynb")]
    nb_files = [os.path.join(nb_path, nb_name) for nb_name in nb_names]
    for nb_file in nb_files:
        os.system("jupyter nbconvert --execute %s" % nb_file)
```

I <i>think</i> that this is the bare minimum we would need to put in a test script to ensure that all tutorial notebooks run properly...

**Comment by r-pascua** [comment]
Some potentially useful things to note:

* Adding the test suggested above will require the travis build to be updated to install extra dependencies. So maybe not the way to go.
* As of writing this, the versions of `pyuvsim` and `pyuvdata` available on PyPI aren't exactly compatible&mdash;in particular, the `pyuvsim.simsetup.initialize_uvdata_from_keywords` uses a keyword argument that's no longer supported by `pyuvdata`.

So it's not exactly a quick fix...

**Comment by steven-murray** [comment]
I think the extra dependency is fine if we can automatically test the
notebooks.
If pyuvsim/pyuvdata aren't compatible, we should make an issue on pyuvsim!
