### ISSUE TITLE
Simulator converts frequencies incorrectly

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#88]
Currently, the `Simulator` class *multiplies* its `data.frequency_array` object by `1e9` rather than dividing. This converts the frequencies to nHz rather than GHz. This is fixed in #74, but should be fixed sooner, given the uncertain merge date of #74.

**Comment by steven-murray** [comment]
Odd... I can't see that anywhere?

**Comment by r-pascua** [comment]
Ah, you're right... It was late and I guess I didn't notice the minus sign. I thought it was strange that something like that could've flown under the radar for so long. Oops! Sorry for the scare!
