### ISSUE TITLE
Add pyradiosky as dependency

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#89]
Things break if `pyradiosky` isn't installed, so we should add it as a dependency.

**Comment by r-pascua** [comment]
Didn't realize this had already been done... Raised the issue because `pyradiosky` didn't end up getting installed alongside `hera_sim` when running `pip install git+https://github.com/hera-team/hera_sim.git`.

**Comment by steven-murray** [comment]
So even with the update and it being a dep, it didn't get installed?

**Comment by r-pascua** [comment]
That seems to be the case. I was fixing up an issue on `uvtools` last night and I had to manually install `pyradiosky` after installing `hera_sim`.

**Comment by steven-murray** [comment]
OK, so yeah it looks like `pyradiosky` is in the `environment.yml`, and so is being installed for tests, but not in the `setup.py`. I think `pyuvsim` has now fixed this on their end anyway, but perhaps that fix is not up on pypi.

**Comment by steven-murray** [comment]
This has been fixed upstream.
