### ISSUE TITLE
test_vis.test_healvis_beam_obsparams does not pass

### ISSUE THREAD

**Issue by Jackmastr** [HERA-Team/hera_sim#92]
ValueError: no field of name flux_density_I. To me there is instead a field of name "I"? Just wanted to confirm it was not just a problem on my end before fixing it since I don't know what change would have caused this.

**Comment by steven-murray** [comment]
I'm not entirely sure what would have caused this -- perhaps an updated healvis? Feel free to fix it if is obvious how to do so!

**Comment by aelanman** [comment]
There was a recent change to `pyradiosky` that replaced `flux_density_I` with `I`, and likewise for the other Stokes parameters. I've pushed a new branch to pyradiosky that should make it backwards-compatible.

Not sure how this came up in a healvis test...

**Comment by steven-murray** [comment]
Certainly have to get back to hera_sim and making it all a bit nicer. That's for next week...
